# Generated by Django 3.0.7 on 2020-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200604_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='imagem')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='nome')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('number', models.CharField(max_length=20, null=True, verbose_name='numero')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'ponto de coleta',
                'verbose_name_plural': 'pontos de coleta',
            },
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='point', to='core.Point'),
        ),
    ]
