# Generated by Django 3.0.7 on 2020-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200605_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.ManyToManyField(related_name='point', to='core.Point'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='título'),
        ),
    ]
