# Generated by Django 3.0.7 on 2020-06-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200605_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='long',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='longitude'),
        ),
    ]
