# Generated by Django 3.0.7 on 2020-06-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200605_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True, verbose_name='longitude'),
        ),
    ]
