# Generated by Django 3.0.7 on 2020-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200605_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='long',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='point',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='point',
            name='uf',
            field=models.CharField(default='', max_length=2, verbose_name='estado'),
        ),
    ]
